spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spm
    username: root
    password: 1234

  amap:
    api:
      key:1d54c645c6787144db43333559498272

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名和下划线命名的自动转换

    #动态sql配置
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.spm.model

